// server/database/types.ts
/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CardStatus = "approved" | "archived" | "changes_requested" | "draft" | "pending_review" | "published" | "rejected" | "review" | "translation_review";

export type FeedbackStatus = "dismissed" | "open" | "resolved";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserStatus = "active" | "banned" | "inactive" | "pending" | "suspended";

export type ReleaseStage = "alfa" | "beta" | "candidate" | "dev" | "release" | "revision";

export interface Arcana {
  code: string;
  content_version_id: number | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  id: Generated<number>;
  image: string | null;
  is_active: Generated<boolean>;
  metadata: Generated<Json | null>;
  modified_at: Generated<Timestamp>;
  sort: Generated<number>;
  status: Generated<CardStatus>;
  updated_by: number | null;
}

export interface ArcanaTranslations {
  arcana_id: number;
  created_by: number | null;
  description: string | null;
  id: Generated<number>;
  language_code: string;
  name: string;
  short_text: string | null;
  updated_by: number | null;
}

export interface BaseCard {
  card_family: string;
  card_type_id: number;
  code: string;
  content_version_id: number | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  /**
   * Efectos narrativos o descriptivos en formato JSONB (Markdown por idioma).
   */
  effects: Generated<Json | null>;
  id: Generated<number>;
  image: string | null;
  is_active: Generated<boolean | null>;
  /**
   * Indica si la carta usa efectos narrativos (legacy) en lugar del sistema semántico.
   */
  legacy_effects: Generated<boolean>;
  /**
   * Campo JSONB para información adicional (propiedades, etiquetas dinámicas, etc.)
   */
  metadata: Generated<Json | null>;
  modified_at: Generated<Timestamp>;
  status: Generated<CardStatus>;
  updated_by: number | null;
}

export interface BaseCardTranslations {
  card_id: number;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  description: string | null;
  id: Generated<number>;
  language_code: string;
  modified_at: Generated<Timestamp>;
  name: string;
  short_text: string | null;
  updated_by: number | null;
}

export interface BaseCardType {
  code: string;
  content_version_id: number | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  id: Generated<number>;
  image: string | null;
  /**
   * Indica si el tipo de carta base está activo.
   */
  is_active: Generated<boolean>;
  metadata: Generated<Json | null>;
  modified_at: Generated<Timestamp>;
  sort: Generated<number>;
  status: Generated<CardStatus>;
  updated_by: number | null;
}

export interface BaseCardTypeTranslations {
  card_type_id: number;
  created_by: number | null;
  description: string | null;
  id: Generated<number>;
  language_code: string;
  name: string;
  short_text: string | null;
  updated_by: number | null;
}

export interface BaseSkills {
  code: string;
  content_version_id: number | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  /**
   * Efectos narrativos o descriptivos en formato JSONB (Markdown por idioma).
   */
  effects: Generated<Json | null>;
  facet_id: number;
  id: Generated<number>;
  image: string | null;
  is_active: Generated<boolean>;
  /**
   * Indica si la habilidad usa efectos narrativos (legacy) en lugar del sistema semántico.
   */
  legacy_effects: Generated<boolean>;
  modified_at: Generated<Timestamp>;
  sort: Generated<number>;
  status: Generated<CardStatus>;
  updated_by: number | null;
}

export interface BaseSkillsTranslations {
  base_skill_id: number;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  description: string | null;
  id: Generated<number>;
  language_code: string;
  modified_at: Generated<Timestamp>;
  name: string;
  short_text: string | null;
  updated_by: number | null;
}

export interface CardEffects {
  condition: string | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  duration: string | null;
  /**
   * Etiqueta semántica que agrupa efectos relacionados o compuestos (ej. vampiric_attack).
   */
  effect_group: string | null;
  effect_target_id: number | null;
  effect_type_id: number | null;
  entity_id: number;
  entity_type: string;
  /**
   * Expresión o referencia a cálculos derivados (half_of_parent_damage, etc.).
   */
  formula: string | null;
  id: Generated<number>;
  is_stackable: Generated<boolean | null>;
  max_stack: number | null;
  metadata: Generated<Json | null>;
  mode: string | null;
  /**
   * Permite jerarquía de efectos (efectos hijos dependientes del efecto padre).
   */
  parent_id: number | null;
  ref_id: number | null;
  ref_type: string | null;
  /**
   * Define el ámbito o sujeto afectado (self, ally, enemy, area, global).
   */
  scope: Generated<string>;
  stack_group: string | null;
  /**
   * Estado de validación visual para el efecto (valid, warning, error).
   */
  validation_state: Generated<string>;
  value: Numeric | null;
}

export interface ContentFeedback {
  category: string | null;
  comment: string;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  entity_id: number;
  entity_type: string;
  id: Generated<number>;
  language_code: string | null;
  resolved_at: Timestamp | null;
  resolved_by: number | null;
  status: Generated<FeedbackStatus>;
  /**
   * Si se indica, el feedback apunta a esa revisión local concreta.
   */
  version_number: number | null;
}

export interface ContentRevisions {
  content_version_id: number | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  /**
   * JSONB con cambios aplicados (p.ej. {"name":{"old":"A","new":"B"}}).
   */
  diff: Generated<Json>;
  entity_id: number;
  entity_type: string;
  id: Generated<number>;
  language_code: string | null;
  next_snapshot: Json | null;
  notes: string | null;
  prev_snapshot: Json | null;
  status: Generated<string>;
  version_number: number;
}

export interface ContentVersions {
  created_at: Generated<Timestamp>;
  created_by: number | null;
  description: string | null;
  id: Generated<number>;
  metadata: Generated<Json>;
  release: ReleaseStage;
  version_semver: string;
}

export interface EffectTarget {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  /**
   * Indica si el target está activo o deshabilitado.
   */
  is_active: Generated<boolean>;
  /**
   * Campo JSONB flexible para parámetros del target (rango, elemento, facet vinculada, etc.).
   */
  metadata: Generated<Json | null>;
  /**
   * Estado editorial del target (draft, review, approved, archived).
   */
  status: Generated<CardStatus>;
  /**
   * Etiqueta semántica o temática para organización (ej. combat, elemental, resource).
   */
  tag: string | null;
  /**
   * Define el ámbito o sujeto afectado (self, ally, enemy, area, global).
   */
  target_scope: string | null;
  /**
   * Estado de validación visual (valid, warning, error).
   */
  validation_state: Generated<string>;
  /**
   * Versión de contenido asociada al target (FK content_versions.id).
   */
  version_id: number | null;
}

export interface EffectTargetTranslations {
  description: string | null;
  effect_target_id: number;
  id: Generated<number>;
  language_code: string;
  name: string;
}

export interface EffectType {
  base_json: Generated<Json | null>;
  /**
   * Categoría funcional del efecto (modifier, condition, trigger, heal, damage, etc.).
   */
  category: Generated<string>;
  code: string;
  created_at: Generated<Timestamp>;
  /**
   * Duración predeterminada de este tipo de efecto (instant, turn, combat, session, permanent).
   */
  default_duration: Generated<string>;
  id: Generated<number>;
  /**
   * Indica si el tipo de efecto está disponible.
   */
  is_active: Generated<boolean>;
  /**
   * Campo JSONB flexible para definir comportamientos adicionales o triggers.
   */
  metadata: Generated<Json>;
  /**
   * Operador aplicado al valor (add, multiply, replace, set, roll, scale).
   */
  operator: Generated<string>;
  /**
   * Estado editorial del tipo de efecto.
   */
  status: Generated<CardStatus>;
  /**
   * Plantilla traducible para renderizar el efecto (+{value} a {target}, etc.).
   */
  template_text: Generated<string>;
  /**
   * Tipo de valor esperado (flat, percent, dice, derived).
   */
  value_type: Generated<string>;
  /**
   * Versión del contenido en la que se definió o actualizó el tipo.
   */
  version_id: number | null;
}

export interface EffectTypeTranslations {
  description: string | null;
  effect_type_id: number;
  id: Generated<number>;
  language_code: string;
  name: string;
  /**
   * Plantilla traducible del efecto en idioma correspondiente.
   */
  template_text: string;
}

export interface Facet {
  arcana_id: number;
  code: string;
  content_version_id: number | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  /**
   * Efectos narrativos o descriptivos en formato JSONB (Markdown por idioma).
   */
  effects: Generated<Json | null>;
  id: Generated<number>;
  image: string | null;
  is_active: Generated<boolean>;
  /**
   * Indica si la faceta usa efectos narrativos (legacy) en lugar del sistema semántico.
   */
  legacy_effects: Generated<boolean>;
  metadata: Generated<Json | null>;
  modified_at: Generated<Timestamp>;
  sort: Generated<number>;
  status: Generated<CardStatus>;
  updated_by: number | null;
}

export interface FacetTranslations {
  created_by: number | null;
  description: string | null;
  facet_id: number;
  id: Generated<number>;
  language_code: string;
  name: string;
  short_text: string | null;
  updated_by: number | null;
}

export interface Roles {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  name: string;
  /**
   * Permisos dinámicos en formato JSONB (ej. {"canEditCards": true}).
   */
  permissions: Generated<Json | null>;
}

export interface TagLinks {
  created_at: Generated<Timestamp>;
  created_by: number | null;
  entity_id: number;
  entity_type: string;
  tag_id: number;
}

export interface Tags {
  category: string;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
  modified_at: Generated<Timestamp>;
  parent_id: number | null;
  sort: Generated<number>;
  updated_by: number | null;
}

export interface TagsTranslations {
  created_at: Generated<Timestamp>;
  created_by: number | null;
  description: string | null;
  id: Generated<number>;
  language_code: string;
  modified_at: Generated<Timestamp>;
  name: string;
  short_text: string | null;
  tag_id: number;
  updated_by: number | null;
}

export interface UserRoles {
  role_id: number;
  user_id: number;
}

export interface Users {
  created_at: Generated<Timestamp>;
  effects: Generated<Json | null>;
  email: string;
  id: Generated<number>;
  image: string | null;
  modified_at: Generated<Timestamp>;
  password_hash: string;
  /**
   * Estado del usuario (active, inactive, banned, pending).
   */
  status: Generated<UserStatus>;
  username: string;
}

export interface VLatestRevision {
  entity_id: number | null;
  entity_type: string | null;
  latest_at: Timestamp | null;
  latest_version: number | null;
}

export interface VOpenFeedback {
  category: string | null;
  comment: string | null;
  created_at: Timestamp | null;
  created_by: number | null;
  entity_id: number | null;
  entity_type: string | null;
  language_code: string | null;
  version_number: number | null;
}

export interface World {
  code: string;
  content_version_id: number | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  id: Generated<number>;
  image: string | null;
  /**
   * Indica si el mundo está activo.
   */
  is_active: Generated<boolean>;
  metadata: Generated<Json | null>;
  modified_at: Generated<Timestamp>;
  status: Generated<CardStatus>;
  updated_by: number | null;
}

export interface WorldCard {
  base_card_id: number | null;
  code: string;
  content_version_id: number | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  /**
   * Efectos narrativos o descriptivos en formato JSONB (Markdown por idioma).
   */
  effects: Generated<Json | null>;
  id: Generated<number>;
  image: string | null;
  /**
   * Indica si la carta del mundo está activa.
   */
  is_active: Generated<boolean>;
  is_override: Generated<boolean | null>;
  /**
   * Indica si la carta del mundo usa efectos narrativos (legacy) en lugar del sistema semántico.
   */
  legacy_effects: Generated<boolean>;
  modified_at: Generated<Timestamp>;
  /**
   * Estado de la carta del mundo (draft, approved, archived, review).
   */
  status: Generated<CardStatus>;
  updated_by: number | null;
  world_id: number;
}

export interface WorldCardTranslations {
  card_id: number;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  description: string | null;
  id: Generated<number>;
  language_code: string;
  modified_at: Generated<Timestamp>;
  name: string;
  short_text: string | null;
  updated_by: number | null;
}

export interface WorldTranslations {
  created_at: Generated<Timestamp>;
  created_by: number | null;
  description: string | null;
  id: Generated<number>;
  language_code: string;
  modified_at: Generated<Timestamp>;
  name: string;
  short_text: string | null;
  updated_by: number | null;
  world_id: number;
}

export interface DB {
  arcana: Arcana;
  arcana_translations: ArcanaTranslations;
  base_card: BaseCard;
  base_card_translations: BaseCardTranslations;
  base_card_type: BaseCardType;
  base_card_type_translations: BaseCardTypeTranslations;
  base_skills: BaseSkills;
  base_skills_translations: BaseSkillsTranslations;
  card_effects: CardEffects;
  content_feedback: ContentFeedback;
  content_revisions: ContentRevisions;
  content_versions: ContentVersions;
  effect_target: EffectTarget;
  effect_target_translations: EffectTargetTranslations;
  effect_type: EffectType;
  effect_type_translations: EffectTypeTranslations;
  facet: Facet;
  facet_translations: FacetTranslations;
  roles: Roles;
  tag_links: TagLinks;
  tags: Tags;
  tags_translations: TagsTranslations;
  user_roles: UserRoles;
  users: Users;
  v_latest_revision: VLatestRevision;
  v_open_feedback: VOpenFeedback;
  world: World;
  world_card: WorldCard;
  world_card_translations: WorldCardTranslations;
  world_translations: WorldTranslations;
}
