// script/translate-missing.mjs
// Traduce automáticamente todas las claves marcadas como TODO
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const ROOT = path.resolve(__dirname, '..')
const LOCALES = path.join(ROOT, 'i18n/locales')

// Traducciones comunes y patrones
const translations = {
  // Common UI elements
  'common.view': { en: 'View', es: 'Ver' },
  'common.username': { en: 'Username', es: 'Nombre de usuario' },
  'common.password': { en: 'Password', es: 'Contraseña' },
  'common.partial': { en: 'Partial', es: 'Parcial' },
  'common.sort': { en: 'Sort', es: 'Ordenar' },
  'common.short_text': { en: 'Short text', es: 'Texto corto' },
  
  // UI actions
  'ui.actions.new': { en: 'New', es: 'Nuevo' },
  'ui.actions.reset': { en: 'Reset', es: 'Restablecer' },
  'ui.actions.download': { en: 'Download', es: 'Descargar' },
  'ui.actions.view': { en: 'View', es: 'Ver' },
  'ui.actions.close': { en: 'Close', es: 'Cerrar' },
  'ui.actions.revert': { en: 'Revert', es: 'Revertir' },
  'ui.actions.copy': { en: 'Copy', es: 'Copiar' },
  'ui.actions.back': { en: 'Back', es: 'Volver' },
  'ui.actions.apply': { en: 'Apply', es: 'Aplicar' },
  'ui.actions.reload': { en: 'Reload', es: 'Recargar' },
  'ui.actions.editJson': { en: 'Edit JSON', es: 'Editar JSON' },
  'ui.actions.quickEdit': { en: 'Quick Edit', es: 'Edición rápida' },
  'ui.actions.fullEdit': { en: 'Full Edit', es: 'Edición completa' },
  
  // Common fields
  'fields.code': { en: 'Code', es: 'Código' },
  'fields.name': { en: 'Name', es: 'Nombre' },
  'fields.category': { en: 'Category', es: 'Categoría' },
  'fields.short_text': { en: 'Short Text', es: 'Texto corto' },
  'fields.description': { en: 'Description', es: 'Descripción' },
  'fields.parent_id': { en: 'Parent', es: 'Padre' },
  'fields.is_active': { en: 'Active', es: 'Activo' },
  'fields.sort': { en: 'Sort Order', es: 'Orden' },
  'fields.facet_id': { en: 'Facet', es: 'Faceta' },
  'fields.language_code': { en: 'Language', es: 'Idioma' },
  'fields.image': { en: 'Image', es: 'Imagen' },
  'fields.status': { en: 'Status', es: 'Estado' },
  'fields.created_by': { en: 'Created By', es: 'Creado por' },
  'fields.content_version_id': { en: 'Content Version', es: 'Versión de contenido' },
  'fields.arcana_id': { en: 'Arcana', es: 'Arcana' },
  'fields.card_type_id': { en: 'Card Type', es: 'Tipo de carta' },
  'fields.effects': { en: 'Effects', es: 'Efectos' },
  'fields.legacy_effects': { en: 'Legacy Effects', es: 'Efectos Legacy' },

  // Tag fields
  'fields.tag.name': { en: 'Tag Name', es: 'Nombre de etiqueta' },
  'fields.tag.code': { en: 'Tag Code', es: 'Código de etiqueta' },
  'fields.tag.category': { en: 'Tag Category', es: 'Categoría de etiqueta' },
  'fields.tag.short_text': { en: 'Short Text', es: 'Texto corto' },
  'fields.tag.description': { en: 'Description', es: 'Descripción' },
  'fields.tag.parent_id': { en: 'Parent Tag', es: 'Etiqueta padre' },
  'fields.tag.is_active': { en: 'Active', es: 'Activo' },
  'fields.tag.sort': { en: 'Sort Order', es: 'Orden' },

  // Skill fields
  'fields.skill.name': { en: 'Skill Name', es: 'Nombre de habilidad' },
  'fields.skill.code': { en: 'Skill Code', es: 'Código de habilidad' },
  'fields.skill.facet_id': { en: 'Facet', es: 'Faceta' },
  'fields.skill.short_text': { en: 'Short Text', es: 'Texto corto' },
  'fields.skill.description': { en: 'Description', es: 'Descripción' },
  'fields.skill.language_code': { en: 'Language', es: 'Idioma' },
  'fields.skill.image': { en: 'Image', es: 'Imagen' },
  'fields.skill.is_active': { en: 'Active', es: 'Activo' },
  'fields.skill.sort': { en: 'Sort Order', es: 'Orden' },
  'fields.skill.status': { en: 'Status', es: 'Estado' },
  
  // UI fields
  'ui.fields.type': { en: 'Type', es: 'Tipo' },
  'ui.fields.id': { en: 'ID', es: 'ID' },
  'ui.fields.metadata': { en: 'Metadata', es: 'Metadatos' },
  'ui.fields.translation': { en: 'Translation', es: 'Traducción' },
  'ui.fields.revisions': { en: 'Revisions', es: 'Revisiones' },
  'ui.fields.createdAt': { en: 'Created at', es: 'Creado el' },
  'ui.fields.updatedAt': { en: 'Updated at', es: 'Actualizado el' },
  'ui.fields.owner': { en: 'Owner', es: 'Propietario' },
  'ui.fields.active': { en: 'Active', es: 'Activo' },
  'ui.fields.author': { en: 'Author', es: 'Autor' },
  'ui.fields.imageUrl': { en: 'Image URL', es: 'URL de imagen' },
  'ui.fields.original': { en: 'Original', es: 'Original' },
  'ui.fields.createdBy': { en: 'Created by', es: 'Creado por' },
  
  // UI states
  'ui.states.unknown': { en: 'Unknown', es: 'Desconocido' },
  'ui.states.enabled': { en: 'Enabled', es: 'Habilitado' },
  'ui.states.disabled': { en: 'Disabled', es: 'Deshabilitado' },
  'ui.states.new': { en: 'New', es: 'Nuevo' },
  
  // UI status badges
  'ui.status.draft': { en: 'Draft', es: 'Borrador' },
  'ui.status.review': { en: 'In Review', es: 'En revisión' },
  'ui.status.pendingReview': { en: 'Pending Review', es: 'Revisión pendiente' },
  'ui.status.translationReview': { en: 'Translation Review', es: 'Revisión de traducción' },
  'ui.status.approved': { en: 'Approved', es: 'Aprobado' },
  'ui.status.published': { en: 'Published', es: 'Publicado' },
  'ui.status.rejected': { en: 'Rejected', es: 'Rechazado' },
  'ui.status.archived': { en: 'Archived', es: 'Archivado' },
  'ui.status.unknown': { en: 'Unknown Status', es: 'Estado desconocido' },
  
  // UI release stages
  'ui.release.dev': { en: 'Development', es: 'Desarrollo' },
  'ui.release.alpha': { en: 'Alpha', es: 'Alfa' },
  'ui.release.beta': { en: 'Beta', es: 'Beta' },
  'ui.release.candidate': { en: 'Release Candidate', es: 'Candidato a lanzamiento' },
  'ui.release.release': { en: 'Release', es: 'Lanzamiento' },
  'ui.release.revision': { en: 'Revision', es: 'Revisión' },
  'ui.release.unknown': { en: 'Unknown Stage', es: 'Etapa desconocida' },
  
  // UI translation status
  'ui.translation.complete': { en: 'Complete', es: 'Completa' },
  'ui.translation.partialFallback': { en: 'Partial (Fallback)', es: 'Parcial (Alternativo)' },
  'ui.translation.missing': { en: 'Missing', es: 'Faltante' },
  'ui.translation.unknown': { en: 'Unknown Translation', es: 'Traducción desconocida' },
  
  // UI labels
  'ui.labels.unsavedChanges': { en: 'Unsaved changes', es: 'Cambios sin guardar' },
  'ui.labels.editMode': { en: 'Edit mode', es: 'Modo edición' },
  'ui.labels.readOnly': { en: 'Read only', es: 'Solo lectura' },
  'ui.common.untitled': { en: 'Untitled', es: 'Sin título' },
  'ui.common.entity': { en: 'Entity', es: 'Entidad' },
  
  // UI sections
  'ui.sections.translations': { en: 'Translations', es: 'Traducciones' },
  'ui.sections.metadata': { en: 'Metadata', es: 'Metadatos' },
  'ui.sections.summary': { en: 'Summary', es: 'Resumen' },
  'ui.sections.basic': { en: 'Basic', es: 'Básico' },
  
  // UI filters
  'ui.filters.any': { en: 'Any', es: 'Cualquiera' },
  'ui.filters.anyDate': { en: 'Any date', es: 'Cualquier fecha' },
  'ui.filters.autoApply': { en: 'Auto apply', es: 'Aplicar automáticamente' },
  
  // UI table
  'ui.table.densityLabel': { en: 'Density', es: 'Densidad' },
  'ui.table.selectAll': { en: 'Select all', es: 'Seleccionar todo' },
  'ui.table.selectRow': { en: 'Select row', es: 'Seleccionar fila' },
  'ui.table.densityComfortable': { en: 'Comfortable', es: 'Cómodo' },
  'ui.table.densityRegular': { en: 'Regular', es: 'Regular' },
  'ui.table.densityCompact': { en: 'Compact', es: 'Compacto' },
  
  // UI notifications
  'ui.notifications.saved': { en: 'Saved', es: 'Guardado' },
  'ui.notifications.errorGeneric': { en: 'An error occurred', es: 'Ocurrió un error' },
  'ui.notifications.notFound': { en: 'Not found', es: 'No encontrado' },
  'ui.notifications.tryAgain': { en: 'Try again', es: 'Inténtalo de nuevo' },
  'ui.notifications.noLanguages': { en: 'No languages', es: 'Sin idiomas' },
  'ui.notifications.noLanguagesDescription': { en: 'No languages available', es: 'No hay idiomas disponibles' },
  
  // UI misc
  'ui.a11y.entityInspectorDescription': { en: 'Entity inspector drawer', es: 'Panel inspector de entidad' },
  'ui.placeholders.json': { en: 'JSON content', es: 'Contenido JSON' },
  'ui.misc.updatedAt': { en: 'Updated', es: 'Actualizado' },
  
  // System statuses
  'system.status.active': { en: 'Active', es: 'Activo' },
  'system.status.inactive': { en: 'Inactive', es: 'Inactivo' },
  'system.status.suspended': { en: 'Suspended', es: 'Suspendido' },
  'system.status.banned': { en: 'Banned', es: 'Baneado' },
  'system.status.pending': { en: 'Pending', es: 'Pendiente' },
  
  // Errors
  'errors.validation': { en: 'Validation error', es: 'Error de validación' },
  'errors.forbidden': { en: 'Forbidden', es: 'Prohibido' },
  'errors.list_failed': { en: 'Failed to load list', es: 'Error al cargar lista' },
  'errors.action_failed': { en: 'Action failed', es: 'La acción falló' },
  'errors.update_failed': { en: 'Update failed', es: 'Error al actualizar' },
  'errors.validation_failed': { en: 'Validation failed', es: 'Validación fallida' },
  'errors.unsupportedEntityTags': { en: 'Unsupported entity tags', es: 'Tags de entidad no soportados' },
  'errors.unsupportedFeedback': { en: 'Unsupported feedback', es: 'Feedback no soportado' },
  
  // Common actions
  'edit': { en: 'Edit', es: 'Editar' },
  'create': { en: 'Create', es: 'Crear' },
  'saved': { en: 'Saved', es: 'Guardado' },
  'close': { en: 'Close', es: 'Cerrar' },
  'submit': { en: 'Submit', es: 'Enviar' },
  'cancel': { en: 'Cancel', es: 'Cancelar' },
  'confirm': { en: 'Confirm', es: 'Confirmar' },
  'remove': { en: 'Remove', es: 'Eliminar' },
  'reset': { en: 'Reset', es: 'Restablecer' },
  'reset-filters': { en: 'Reset filters', es: 'Restablecer filtros' },
  'remove-image': { en: 'Remove image', es: 'Eliminar imagen' },
  'active': { en: 'Active', es: 'Activo' },
  'inactive': { en: 'Inactive', es: 'Inactivo' },
  
  // Features - Admin
  'features.admin.entityViewer.title': { en: 'Entity Viewer', es: 'Visor de Entidades' },
  'features.admin.entityViewer.subtitle': { en: 'Inspect entity data and metadata', es: 'Inspecciona datos y metadatos de entidades' },
  'features.admin.entityViewer.empty': { en: 'No entity selected', es: 'No hay entidad seleccionada' },
  'features.admin.entityViewer.viewJson': { en: 'View JSON', es: 'Ver JSON' },
  'features.admin.feedback.notes.description': { en: 'Internal notes for this feedback', es: 'Notas internas para este feedback' },
  'features.admin.feedback.advancedFilters': { en: 'Advanced Filters', es: 'Filtros Avanzados' },
  'features.admin.dashboardTitle': { en: 'Admin Dashboard', es: 'Panel de Administración' },
  'features.admin.dashboardSubtitle': { en: 'System overview and management', es: 'Vista general y gestión del sistema' },
  'features.admin.usersTitle': { en: 'Users Management', es: 'Gestión de Usuarios' },
  'features.admin.usersSubtitle': { en: 'Manage user accounts and permissions', es: 'Gestionar cuentas de usuario y permisos' },
  'features.admin.usersSummary': { en: 'User accounts and permissions', es: 'Cuentas de usuario y permisos' },
  'features.admin.usersHighlight1': { en: 'Manage roles and access', es: 'Gestionar roles y acceso' },
  'features.admin.usersHighlight2': { en: 'Monitor user activity', es: 'Monitorear actividad de usuarios' },
  'features.admin.usersCta': { en: 'Manage Users', es: 'Gestionar Usuarios' },
  'features.admin.versionsSummary': { en: 'Content versions and releases', es: 'Versiones de contenido y lanzamientos' },
  'features.admin.versionsHighlight1': { en: 'Track content changes', es: 'Rastrear cambios de contenido' },
  'features.admin.versionsHighlight2': { en: 'Manage releases', es: 'Gestionar lanzamientos' },
  'features.admin.versionsCta': { en: 'Manage Versions', es: 'Gestionar Versiones' },
  'features.admin.feedbackSummary': { en: 'User feedback and suggestions', es: 'Feedback y sugerencias de usuarios' },
  'features.admin.feedbackHighlight1': { en: 'Review user reports', es: 'Revisar reportes de usuarios' },
  'features.admin.feedbackHighlight2': { en: 'Track improvement requests', es: 'Rastrear solicitudes de mejora' },
  'features.admin.feedbackCta': { en: 'Manage Feedback', es: 'Gestionar Feedback' },
  'features.admin.databaseTitle': { en: 'Database Management', es: 'Gestión de Base de Datos' },
  'features.admin.databaseSummary': { en: 'Database operations and maintenance', es: 'Operaciones y mantenimiento de base de datos' },
  'features.admin.databaseHighlight1': { en: 'Backup and restore', es: 'Respaldo y restauración' },
  'features.admin.databaseHighlight2': { en: 'Performance monitoring', es: 'Monitoreo de rendimiento' },
  'features.admin.databaseCta': { en: 'Manage Database', es: 'Gestionar Base de Datos' },
}

// Función para generar traducciones automáticamente
function generateTranslation(key, locale) {
  // Si tenemos una traducción predefinida, usarla
  if (translations[key] && translations[key][locale]) {
    return translations[key][locale]
  }
  
  // Patrón especial para campos de entidad: fields.<entity>.<field>
  if (key.startsWith('fields.') && key.split('.').length === 3) {
    const [, entity, field] = key.split('.')
    const entityName = generateTranslation(`entities.${entity}`, locale) || entity
    const fieldName = generateTranslation(`fields.${field}`, locale) || generateTranslation(`ui.fields.${field}`, locale) || field
    
    // Limpiar si devolvió el fallback
    const cleanEntity = entityName.includes('TODO') ? entity.replace(/_/g, ' ') : entityName
    const cleanField = fieldName.includes('TODO') ? field.replace(/_/g, ' ') : fieldName
    
    // Capitalizar
    const capEntity = cleanEntity.charAt(0).toUpperCase() + cleanEntity.slice(1)
    const capField = cleanField.charAt(0).toUpperCase() + cleanField.slice(1)
    
    if (locale === 'es') {
      return `${capField} de ${capEntity.toLowerCase()}`
    } else {
      return `${capEntity} ${capField}`
    }
  }
  
  // Generar traducción basada en patrones
  const parts = key.split('.')
  const lastPart = parts[parts.length - 1]
  
  // Patrones comunes
  const patterns = {
    en: {
      title: 'Title',
      subtitle: 'Subtitle',
      description: 'Description',
      empty: 'Empty',
      placeholder: 'Placeholder',
      hint: 'Hint',
      label: 'Label',
      button: 'Button',
      link: 'Link',
      text: 'Text',
      content: 'Content',
      message: 'Message',
      error: 'Error',
      warning: 'Warning',
      info: 'Info',
      success: 'Success',
      loading: 'Loading',
      saving: 'Saving',
      deleting: 'Deleting',
      creating: 'Creating',
      updating: 'Updating',
      editing: 'Editing',
      viewing: 'Viewing',
      managing: 'Managing',
      configuring: 'Configuring',
      settings: 'Settings',
      options: 'Options',
      preferences: 'Preferences',
      filters: 'Filters',
      search: 'Search',
      results: 'Results',
      list: 'List',
      grid: 'Grid',
      table: 'Table',
      card: 'Card',
      modal: 'Modal',
      dialog: 'Dialog',
      drawer: 'Drawer',
      menu: 'Menu',
      navigation: 'Navigation',
      header: 'Header',
      footer: 'Footer',
      sidebar: 'Sidebar',
      main: 'Main',
      section: 'Section',
      group: 'Group',
      item: 'Item',
      element: 'Element',
      component: 'Component',
      page: 'Page',
      view: 'View',
      layout: 'Layout',
      template: 'Template',
      style: 'Style',
      theme: 'Theme',
      design: 'Design',
      interface: 'Interface',
      user: 'User',
      admin: 'Administrator',
      manager: 'Manager',
      editor: 'Editor',
      viewer: 'Viewer',
      guest: 'Guest',
      public: 'Public',
      private: 'Private',
      secure: 'Secure',
      safe: 'Safe',
      trusted: 'Trusted',
      verified: 'Verified',
      approved: 'Approved',
      rejected: 'Rejected',
      pending: 'Pending',
      completed: 'Completed',
      cancelled: 'Cancelled',
      aborted: 'Aborted',
      failed: 'Failed',
      debug: 'Debug',
      trace: 'Trace',
      log: 'Log',
      audit: 'Audit',
      history: 'History',
      timeline: 'Timeline',
      calendar: 'Calendar',
      date: 'Date',
      time: 'Time',
      datetime: 'Date & Time',
      period: 'Period',
      duration: 'Duration',
      interval: 'Interval',
      frequency: 'Frequency',
      rate: 'Rate',
      speed: 'Speed',
      size: 'Size',
      length: 'Length',
      width: 'Width',
      height: 'Height',
      weight: 'Weight',
      volume: 'Volume',
      area: 'Area',
      distance: 'Distance',
      position: 'Position',
      location: 'Location',
      address: 'Address',
      coordinates: 'Coordinates',
      map: 'Map',
      region: 'Region',
      zone: 'Zone',
      district: 'District',
      neighborhood: 'Neighborhood',
      city: 'City',
      state: 'State',
      country: 'Country',
      continent: 'Continent',
      world: 'World',
      universe: 'Universe',
      galaxy: 'Galaxy',
      star: 'Star',
      planet: 'Planet',
      moon: 'Moon',
      sun: 'Sun',
      earth: 'Earth',
      mars: 'Mars',
      venus: 'Venus',
      mercury: 'Mercury',
      jupiter: 'Jupiter',
      saturn: 'Saturn',
      uranus: 'Uranus',
      neptune: 'Neptune',
      pluto: 'Pluto'
    },
    es: {
      title: 'Título',
      subtitle: 'Subtítulo',
      description: 'Descripción',
      empty: 'Vacío',
      placeholder: 'Marcador de posición',
      hint: 'Pista',
      label: 'Etiqueta',
      button: 'Botón',
      link: 'Enlace',
      text: 'Texto',
      content: 'Contenido',
      message: 'Mensaje',
      error: 'Error',
      warning: 'Advertencia',
      info: 'Información',
      success: 'Éxito',
      loading: 'Cargando',
      saving: 'Guardando',
      deleting: 'Eliminando',
      creating: 'Creando',
      updating: 'Actualizando',
      editing: 'Editando',
      viewing: 'Viendo',
      managing: 'Gestionando',
      configuring: 'Configurando',
      settings: 'Configuración',
      options: 'Opciones',
      preferences: 'Preferencias',
      filters: 'Filtros',
      search: 'Buscar',
      results: 'Resultados',
      list: 'Lista',
      grid: 'Cuadrícula',
      table: 'Tabla',
      card: 'Tarjeta',
      modal: 'Modal',
      dialog: 'Diálogo',
      drawer: 'Panel',
      menu: 'Menú',
      navigation: 'Navegación',
      header: 'Encabezado',
      footer: 'Pie de página',
      sidebar: 'Barra lateral',
      main: 'Principal',
      section: 'Sección',
      group: 'Grupo',
      item: 'Elemento',
      element: 'Elemento',
      component: 'Componente',
      page: 'Página',
      view: 'Vista',
      layout: 'Diseño',
      template: 'Plantilla',
      style: 'Estilo',
      theme: 'Tema',
      design: 'Diseño',
      interface: 'Interfaz',
      user: 'Usuario',
      admin: 'Administrador',
      manager: 'Gestor',
      editor: 'Editor',
      viewer: 'Visor',
      guest: 'Invitado',
      public: 'Público',
      private: 'Privado',
      secure: 'Seguro',
      safe: 'Seguro',
      trusted: 'Confiable',
      verified: 'Verificado',
      approved: 'Aprobado',
      rejected: 'Rechazado',
      pending: 'Pendiente',
      completed: 'Completado',
      cancelled: 'Cancelado',
      aborted: 'Abortado',
      failed: 'Fallido',
      debug: 'Depurar',
      trace: 'Traza',
      log: 'Registro',
      audit: 'Auditoría',
      history: 'Historial',
      timeline: 'Línea de tiempo',
      calendar: 'Calendario',
      date: 'Fecha',
      time: 'Hora',
      datetime: 'Fecha y Hora',
      period: 'Período',
      duration: 'Duración',
      interval: 'Intervalo',
      frequency: 'Frecuencia',
      rate: 'Tasa',
      speed: 'Velocidad',
      size: 'Tamaño',
      length: 'Longitud',
      width: 'Ancho',
      height: 'Alto',
      weight: 'Peso',
      volume: 'Volumen',
      area: 'Área',
      distance: 'Distancia',
      position: 'Posición',
      location: 'Ubicación',
      address: 'Dirección',
      coordinates: 'Coordenadas',
      map: 'Mapa',
      region: 'Región',
      zone: 'Zona',
      district: 'Distrito',
      neighborhood: 'Barrio',
      city: 'Ciudad',
      state: 'Estado',
      country: 'País',
      continent: 'Continente',
      world: 'Mundo',
      universe: 'Universo',
      galaxy: 'Galaxia',
      star: 'Estrella',
      planet: 'Planeta',
      moon: 'Luna',
      sun: 'Sol',
      earth: 'Tierra',
      mars: 'Marte',
      venus: 'Venus',
      mercury: 'Mercurio',
      jupiter: 'Júpiter',
      saturn: 'Saturno',
      uranus: 'Urano',
      neptune: 'Neptuno',
      pluto: 'Plutón'
    }
  }
  
  // Si el patrón existe, usarlo
  if (patterns[locale] && patterns[locale][lastPart]) {
    return patterns[locale][lastPart]
  }
  
  // Convertir camelCase a Title Case
  const titleCase = lastPart
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, str => str.toUpperCase())
    .trim()
  
  if (locale === 'es') {
    // Traducción simple al español
    const simpleTranslations = {
      'Title': 'Título',
      'Description': 'Descripción',
      'Name': 'Nombre',
      'Email': 'Correo electrónico',
      'Phone': 'Teléfono',
      'Address': 'Dirección',
      'City': 'Ciudad',
      'Country': 'País',
      'Status': 'Estado',
      'Type': 'Tipo',
      'Category': 'Categoría',
      'Tag': 'Etiqueta',
      'Label': 'Etiqueta',
      'Value': 'Valor',
      'Count': 'Cantidad',
      'Total': 'Total',
      'Price': 'Precio',
      'Cost': 'Costo',
      'Date': 'Fecha',
      'Time': 'Hora',
      'Created': 'Creado',
      'Updated': 'Actualizado',
      'Deleted': 'Eliminado',
      'Active': 'Activo',
      'Inactive': 'Inactivo',
      'Enabled': 'Habilitado',
      'Disabled': 'Deshabilitado',
      'Public': 'Público',
      'Private': 'Privado',
      'Visible': 'Visible',
      'Hidden': 'Oculto',
      'Required': 'Requerido',
      'Optional': 'Opcional',
      'Search': 'Buscar',
      'Filter': 'Filtrar',
      'Sort': 'Ordenar',
      'Edit': 'Editar',
      'Save': 'Guardar',
      'Cancel': 'Cancelar',
      'Delete': 'Eliminar',
      'Create': 'Crear',
      'Update': 'Actualizar',
      'View': 'Ver',
      'Show': 'Mostrar',
      'Hide': 'Ocultar',
      'Open': 'Abrir',
      'Close': 'Cerrar',
      'Start': 'Iniciar',
      'Stop': 'Detener',
      'Pause': 'Pausar',
      'Resume': 'Reanudar',
      'Continue': 'Continuar',
      'Finish': 'Finalizar',
      'Complete': 'Completar',
      'Submit': 'Enviar',
      'Send': 'Enviar',
      'Receive': 'Recibir',
      'Download': 'Descargar',
      'Upload': 'Subir',
      'Import': 'Importar',
      'Export': 'Exportar',
      'Copy': 'Copiar',
      'Move': 'Mover',
      'Rename': 'Renombrar',
      'Duplicate': 'Duplicar',
      'Merge': 'Fusionar',
      'Split': 'Dividir',
      'Join': 'Unir',
      'Connect': 'Conectar',
      'Disconnect': 'Desconectar',
      'Link': 'Enlazar',
      'Unlink': 'Desenlazar',
      'Attach': 'Adjuntar',
      'Detach': 'Desadjuntar',
      'Add': 'Agregar',
      'Remove': 'Quitar',
      'Insert': 'Insertar',
      'Extract': 'Extraer',
      'Select': 'Seleccionar',
      'Deselect': 'Deseleccionar',
      'Choose': 'Elegir',
      'Pick': 'Escoger',
      'Accept': 'Aceptar',
      'Reject': 'Rechazar',
      'Approve': 'Aprobar',
      'Deny': 'Denegar',
      'Allow': 'Permitir',
      'Block': 'Bloquear',
      'Ban': 'Banear',
      'Unban': 'Desbanear',
      'Suspend': 'Suspender',
      'Reactivate': 'Reactivar',
      'Enable': 'Habilitar',
      'Disable': 'Deshabilitar',
      'Activate': 'Activar',
      'Deactivate': 'Desactivar',
      'Install': 'Instalar',
      'Uninstall': 'Desinstalar',
      'Setup': 'Configurar',
      'Configure': 'Configurar',
      'Customize': 'Personalizar',
      'Reset': 'Restablecer',
      'Restore': 'Restaurar',
      'Backup': 'Respaldo',
      'Archive': 'Archivar',
      'Unarchive': 'Desarchivar',
      'Lock': 'Bloquear',
      'Unlock': 'Desbloquear',
      'Secure': 'Asegurar',
      'Protect': 'Proteger',
      'Share': 'Compartir',
      'Publish': 'Publicar',
      'Unpublish': 'Despublicar',
      'Release': 'Liberar',
      'Deploy': 'Desplegar',
      'Test': 'Probar',
      'Debug': 'Depurar',
      'Monitor': 'Monitorear',
      'Track': 'Rastrear',
      'Log': 'Registrar',
      'Audit': 'Auditar',
      'Review': 'Revisar',
      'Check': 'Verificar',
      'Validate': 'Validar',
      'Verify': 'Verificar',
      'Confirm': 'Confirmar',
      'Authorize': 'Autorizar',
      'Authenticate': 'Autenticar',
      'Login': 'Iniciar sesión',
      'Logout': 'Cerrar sesión',
      'Register': 'Registrar',
      'Signup': 'Registrarse',
      'Signin': 'Iniciar sesión',
      'Signout': 'Cerrar sesión',
      'Profile': 'Perfil',
      'Account': 'Cuenta',
      'Settings': 'Configuración',
      'Preferences': 'Preferencias',
      'Options': 'Opciones',
      'Tools': 'Herramientas',
      'Help': 'Ayuda',
      'Support': 'Soporte',
      'About': 'Acerca de',
      'Info': 'Información',
      'Details': 'Detalles',
      'More': 'Más',
      'Less': 'Menos',
      'All': 'Todos',
      'None': 'Ninguno',
      'Any': 'Cualquiera',
      'Some': 'Algunos',
      'Many': 'Muchos',
      'Few': 'Pocos',
      'First': 'Primero',
      'Last': 'Último',
      'Next': 'Siguiente',
      'Previous': 'Anterior',
      'Current': 'Actual',
      'New': 'Nuevo',
      'Old': 'Viejo',
      'Recent': 'Reciente',
      'Latest': 'Último',
      'Popular': 'Popular',
      'Featured': 'Destacado',
      'Recommended': 'Recomendado',
      'Suggested': 'Sugerido',
      'Related': 'Relacionado',
      'Similar': 'Similar',
      'Matching': 'Coincidente',
      'Available': 'Disponible',
      'Unavailable': 'No disponible',
      'Online': 'En línea',
      'Offline': 'Sin conexión',
      'Connected': 'Conectado',
      'Disconnected': 'Desconectado',
      'Ready': 'Listo',
      'Busy': 'Ocupado',
      'Loading': 'Cargando',
      'Processing': 'Procesando',
      'Incomplete': 'Incompleto',
      'Failure': 'Fallo',
      'Trace': 'Traza',
      'Verbose': 'Detallado',
      'Quiet': 'Silencioso',
      'Normal': 'Normal',
      'Default': 'Predeterminado',
      'Custom': 'Personalizado',
      'Standard': 'Estándar',
      'Advanced': 'Avanzado',
      'Basic': 'Básico',
      'Simple': 'Simple',
      'Complex': 'Complejo',
      'Easy': 'Fácil',
      'Difficult': 'Difícil',
      'Hard': 'Difícil',
      'Soft': 'Suave',
      'Rough': 'Áspero',
      'Smooth': 'Suave',
      'Sharp': 'Afilado',
      'Blunt': 'Rom',
      'Hot': 'Caliente',
      'Cold': 'Frío',
      'Warm': 'Tibio',
      'Cool': 'Fresco',
      'Dry': 'Seco',
      'Wet': 'Mojado',
      'Light': 'Ligero',
      'Heavy': 'Pesado',
      'Big': 'Grande',
      'Small': 'Pequeño',
      'Large': 'Grande',
      'Tiny': 'Diminuto',
      'Huge': 'Enorme',
      'Giant': 'Gigante',
      'Mini': 'Mini',
      'Micro': 'Micro',
      'Macro': 'Macro',
      'Nano': 'Nano',
      'Mega': 'Mega',
      'Giga': 'Giga',
      'Tera': 'Tera',
      'Kilo': 'Kilo',
      'Milli': 'Mili',
      'Centi': 'Centi',
      'Deci': 'Deci',
      'Deca': 'Deca',
      'Hecto': 'Hecto'
    }
    
    return simpleTranslations[titleCase] || titleCase
  }
  
  // Para inglés, devolver el title case
  return titleCase
}

// Función para procesar un archivo de idioma
function processFile(filename, locale) {
  const filePath = path.join(LOCALES, filename)
  const content = fs.readFileSync(filePath, 'utf8')
  let modified = false
  
  // Reemplazar todas las claves TODO
  const newContent = content.replace(/"([^"]+)":\s*"TODO: Translate [^"]+"/g, (match, key) => {
    const translation = generateTranslation(key, locale)
    modified = true
    return `"${key}": "${translation}"`
  })
  
  if (modified) {
    fs.writeFileSync(filePath, newContent, 'utf8')
    return true
  }
  
  return false
}

// Main
console.log('🔄 Traduciendo claves faltantes...')

const enModified = processFile('en.json', 'en')
const esModified = processFile('es.json', 'es')

if (enModified) {
  console.log('✅ en.json actualizado')
}

if (esModified) {
  console.log('✅ es.json actualizado')
}

if (!enModified && !esModified) {
  console.log('ℹ️  No había claves por traducir')
} else {
  console.log('\n✨ Traducciones completadas!')
  console.log('\n📝 Nota: Algunas traducciones pueden necesitar revisión manual.')
  console.log('   Ejecuta "grep -c \'TODO: Translate\' i18n/locales/*.json" para verificar.')
}
